[versions]

compose-activity = "1.9.2"
core = "1.13.1"
assertk = "0.28.1"
compose-test = "1.7.3"

kotlin = "2.0.20"
android = "8.7.0"
compose = "1.6.11"

sdk-min = "24"
sdk-compile = "34"
sdk-target = "34"

[libraries]

compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }
compose-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "compose-test" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = 'compose-test' }

[plugins]

kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android = { id = "com.android.application", version.ref = "android" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }